version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    container_name: mongodb

  app1:
    build: .
    depends_on:
      - redis
      - mongodb
    ports:
      - "8081:8080"

  app2:
    build: .
    depends_on:
      - redis
      - mongodb
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
