version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  mongodb:
    image: mongo
    restart: always
    networks:
      - default
    ports:
      - "27017:27017"
    container_name: mongodb


  app:
    build: .
    depends_on:
      - redis
      - mongodb
    ports:
      - "8080:8080"
